name: Post Submit

on:
  pull_request:
    branches:
      - master
    types:
      - closed

permissions:
  id-token: write
  contents: read

jobs:
  Push:
    runs-on: ubuntu-latest
    env:
      IMAGE_REGISTRY_PATH: ${{ secrets.IMAGE_REGISTRY_PREFIX }}/risken-code
    if: github.event.pull_request.merged == true
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: deploy-role-session
          aws-region: ap-northeast-1
      - run: aws sts get-caller-identity
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set token for access internal repository
        run: git config --global url."https://${{ secrets.GO_MODULES_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: "1.14"

      - name: Tests
        run: make go-test -j

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ github.sha }}
            ${{ runner.os }}-buildx-
            refs/head/master

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Push Code Images
        uses: docker/build-push-action@v2
        with:
          context: src/code
          platforms: linux/amd64,linux/arm64
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ env.IMAGE_REGISTRY_PATH }}/code:${{ github.sha }}
            ${{ env.IMAGE_REGISTRY_PATH }}/code:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          secrets: |
            "GITHUB_TOKEN=${{ secrets.GO_MODULES_TOKEN }}"
            "GITHUB_USER=${{ secrets.GO_MODULES_USER }}"

      - name: Push Gitleaks Images
        uses: docker/build-push-action@v2
        with:
          context: src/gitleaks
          platforms: linux/amd64,linux/arm64
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ env.IMAGE_REGISTRY_PATH }}/gitleaks:${{ github.sha }}
            ${{ env.IMAGE_REGISTRY_PATH }}/gitleaks:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          secrets: |
            "GITHUB_TOKEN=${{ secrets.GO_MODULES_TOKEN }}"
            "GITHUB_USER=${{ secrets.GO_MODULES_USER }}"
